### ISSUE TITLE
mvnd archetype:generate failed

### ISSUE THREAD

**Issue by jorgaf** [apache/maven-mvnd#1036]
Hello,

I am trying to use mvnd with de archetype generate and I get this error:

[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
Exception in thread "main" java.lang.ClassCastException: org.mvndaemon.mvnd.common.Message$ProjectEvent cannot be cast to org.mvndaemon.mvnd.common.Message$StringMessage
	at org.mvndaemon.mvnd.common.logging.TerminalOutput.doAccept(TerminalOutput.java:315)
	at org.mvndaemon.mvnd.common.logging.TerminalOutput.accept(TerminalOutput.java:213)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:372)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:163)

I am working with:
Apache Maven Daemon (mvnd) 1.0.0 darwin-amd64 native client (0cb7cbcbed6fad010b14dcd05acdc0a59685d88d)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jni.osx.OsXNativePty
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /👻/.sdkman/candidates/mvnd/current/mvn
Java version: 22, vendor: Oracle Corporation, runtime: /👻/.sdkman/candidates/java/22-open
Default locale: es_EC, platform encoding: UTF-8
OS name: "mac os x", version: "13.6.7", arch: "x86_64", family: "mac"

**Comment by cstamas** [comment]
Affects both: 1.0.0 and 2.0.0-beta-1

**Comment by cstamas** [comment]
Please retest with binaries built by CI from here:
https://github.com/apache/maven-mvnd/actions/runs/9597334445
