### ISSUE TITLE
MultipleArtifactsNotFoundException: Missing: org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2

### ISSUE THREAD

**Issue by ppalaga** [apache/maven-mvnd#256]
This happens on the CI randomly:

```
2020-12-10T12:31:53.1991650Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project multi-module-hi: Unable to generate classpath: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
2020-12-10T12:31:53.1994845Z ----------
2020-12-10T12:31:53.1995706Z 1) org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2
2020-12-10T12:31:53.1996314Z 
2020-12-10T12:31:53.1997029Z   Try downloading the file manually from the project website.
2020-12-10T12:31:53.1997495Z 
2020-12-10T12:31:53.1997920Z   Then, install it using the command: 
2020-12-10T12:31:53.1999441Z       mvn install:install-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit-platform -Dversion=2.22.2 -Dpackaging=jar -Dfile=/path/to/file
2020-12-10T12:31:53.2000472Z 
2020-12-10T12:31:53.2001303Z   Alternatively, if you host your own repository you can deploy the file there: 
2020-12-10T12:31:53.2003179Z       mvn deploy:deploy-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit-platform -Dversion=2.22.2 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
2020-12-10T12:31:53.2004332Z 
2020-12-10T12:31:53.2004731Z   Path to dependency: 
2020-12-10T12:31:53.2005185Z   	1) dummy:dummy:jar:1.0
2020-12-10T12:31:53.2006186Z   	2) org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2
2020-12-10T12:31:53.2006838Z 
2020-12-10T12:31:53.2007283Z ----------
2020-12-10T12:31:53.2007748Z 1 required artifact is missing.
2020-12-10T12:31:53.2008077Z 
2020-12-10T12:31:53.2008439Z for artifact: 
2020-12-10T12:31:53.2008844Z   dummy:dummy:jar:1.0
2020-12-10T12:31:53.2009129Z 
2020-12-10T12:31:53.2009607Z from the specified remote repositories:
2020-12-10T12:31:53.2010607Z   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
2020-12-10T12:31:53.2011327Z 
2020-12-10T12:31:53.2012646Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
2020-12-10T12:31:53.2014956Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
2020-12-10T12:31:53.2017276Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
2020-12-10T12:31:53.2020871Z 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
2020-12-10T12:31:53.2023934Z 	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
2020-12-10T12:31:53.2026209Z 	at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
2020-12-10T12:31:53.2028065Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-12-10T12:31:53.2029484Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-12-10T12:31:53.2031306Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-10T12:31:53.2033184Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-10T12:31:53.2034424Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-10T12:31:53.2036980Z Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to generate classpath: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
2020-12-10T12:31:53.2039490Z ----------
2020-12-10T12:31:53.2040360Z 1) org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2
2020-12-10T12:31:53.2041059Z 
2020-12-10T12:31:53.2041576Z   Try downloading the file manually from the project website.
2020-12-10T12:31:53.2042007Z 
2020-12-10T12:31:53.2042418Z   Then, install it using the command: 
2020-12-10T12:31:53.2043830Z       mvn install:install-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit-platform -Dversion=2.22.2 -Dpackaging=jar -Dfile=/path/to/file
2020-12-10T12:31:53.2044782Z 
2020-12-10T12:31:53.2045354Z   Alternatively, if you host your own repository you can deploy the file there: 
2020-12-10T12:31:53.2047398Z       mvn deploy:deploy-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit-platform -Dversion=2.22.2 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
2020-12-10T12:31:53.2048562Z 
2020-12-10T12:31:53.2048958Z   Path to dependency: 
2020-12-10T12:31:53.2049423Z   	1) dummy:dummy:jar:1.0
2020-12-10T12:31:53.2050402Z   	2) org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2
2020-12-10T12:31:53.2051063Z 
2020-12-10T12:31:53.2051510Z ----------
2020-12-10T12:31:53.2051975Z 1 required artifact is missing.
2020-12-10T12:31:53.2052307Z 
2020-12-10T12:31:53.2052671Z for artifact: 
2020-12-10T12:31:53.2053077Z   dummy:dummy:jar:1.0
2020-12-10T12:31:53.2053354Z 
2020-12-10T12:31:53.2053837Z from the specified remote repositories:
2020-12-10T12:31:53.2054843Z   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
2020-12-10T12:31:53.2055558Z 
2020-12-10T12:31:53.2057814Z 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createStartupConfiguration(AbstractSurefireMojo.java:1735)
2020-12-10T12:31:53.2061606Z 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createForkStarter(AbstractSurefireMojo.java:2128)
2020-12-10T12:31:53.2064856Z 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1180)
2020-12-10T12:31:53.2068637Z 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
2020-12-10T12:31:53.2072204Z 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
2020-12-10T12:31:53.2074938Z 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
2020-12-10T12:31:53.2077752Z 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
2020-12-10T12:31:53.2079148Z 	... 10 common frames omitted
2020-12-10T12:31:53.2081170Z Caused by: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
2020-12-10T12:31:53.2082896Z ----------
2020-12-10T12:31:53.2083777Z 1) org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2
2020-12-10T12:31:53.2084368Z 
2020-12-10T12:31:53.2084894Z   Try downloading the file manually from the project website.
2020-12-10T12:31:53.2085425Z 
2020-12-10T12:31:53.2085823Z   Then, install it using the command: 
2020-12-10T12:31:53.2087258Z       mvn install:install-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit-platform -Dversion=2.22.2 -Dpackaging=jar -Dfile=/path/to/file
2020-12-10T12:31:53.2088200Z 
2020-12-10T12:31:53.2088791Z   Alternatively, if you host your own repository you can deploy the file there: 
2020-12-10T12:31:53.2090503Z       mvn deploy:deploy-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit-platform -Dversion=2.22.2 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
2020-12-10T12:31:53.2091568Z 
2020-12-10T12:31:53.2091949Z   Path to dependency: 
2020-12-10T12:31:53.2092369Z   	1) dummy:dummy:jar:1.0
2020-12-10T12:31:53.2093268Z   	2) org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2
2020-12-10T12:31:53.2093874Z 
2020-12-10T12:31:53.2094301Z ----------
2020-12-10T12:31:53.2094714Z 1 required artifact is missing.
2020-12-10T12:31:53.2095038Z 
2020-12-10T12:31:53.2095430Z for artifact: 
2020-12-10T12:31:53.2095826Z   dummy:dummy:jar:1.0
2020-12-10T12:31:53.2096070Z 
2020-12-10T12:31:53.2096704Z from the specified remote repositories:
2020-12-10T12:31:53.2097691Z   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
2020-12-10T12:31:53.2098407Z 
2020-12-10T12:31:53.2100703Z 	at org.apache.maven.artifact.resolver.DefaultResolutionErrorHandler.throwErrors(DefaultResolutionErrorHandler.java:73)
2020-12-10T12:31:53.2105022Z 	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveWithExceptions(DefaultArtifactResolver.java:364)
2020-12-10T12:31:53.2109263Z 	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:352)
2020-12-10T12:31:53.2113147Z 	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:324)
2020-12-10T12:31:53.2117023Z 	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:287)
2020-12-10T12:31:53.2121018Z 	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:261)
2020-12-10T12:31:53.2125000Z 	at org.apache.maven.plugin.surefire.SurefireDependencyResolver.resolveArtifact(SurefireDependencyResolver.java:130)
2020-12-10T12:31:53.2129333Z 	at org.apache.maven.plugin.surefire.SurefireDependencyResolver.getProviderClasspath(SurefireDependencyResolver.java:143)
2020-12-10T12:31:53.2133308Z 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo$JUnitPlatformProviderInfo.getProviderClasspath(AbstractSurefireMojo.java:2929)
2020-12-10T12:31:53.2137022Z 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createStartupConfiguration(AbstractSurefireMojo.java:1721)
2020-12-10T12:31:53.2139352Z 	... 16 common frames omitted'}
2020-12-10T12:31:53.2140199Z ProjectLogMessage{projectId='multi-module', message='[ERROR] '}
2020-12-10T12:31:53.2141513Z ProjectLogMessage{projectId='multi-module', message='[ERROR] Re-run Maven using the -X switch to enable full debug logging.'}
2020-12-10T12:31:53.2142763Z ProjectLogMessage{projectId='multi-module', message='[ERROR] '}
2020-12-10T12:31:53.2144244Z ProjectLogMessage{projectId='multi-module', message='[ERROR] For more information about the errors and possible solutions, please read the following articles:'}
2020-12-10T12:31:53.2146198Z ProjectLogMessage{projectId='multi-module', message='[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException'}
2020-12-10T12:31:53.2147961Z ProjectLogMessage{projectId='multi-module', message='[ERROR] '}
2020-12-10T12:31:53.2149423Z ProjectLogMessage{projectId='multi-module', message='[ERROR] After correcting the problems, you can resume the build with the command'}
2020-12-10T12:31:53.2150968Z ProjectLogMessage{projectId='multi-module', message='[ERROR]   mvn <args> -rf :multi-module-hi'}
```

**Comment by ppalaga** [comment]
Duplicate of https://github.com/mvndaemon/mvnd/issues/281
