### ISSUE TITLE
jdk 1.8 exception

### ISSUE THREAD

**Issue by elliotliu** [apache/maven-mvnd#544]
download release version is ok.

use brew install mvnd, mvnd --version

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mvndaemon/mvnd/client/DefaultClient has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by kimvon** [comment]
i read release0.7.1 description showing close issue "Different java versions for mvnd and maven #512" , the issue suggest that we can use JDK11 runtime for all and set the --release 8 which produces JDK8 compatible code., such as,
 mvnd -Dmaven.compiler.release=8 compile.

as well as , the issue say that the mvnd needs at minimum JDK8 to run......maybe mvnd can run in jdk8 and we need to build mvnd from source in jdk 8 in order to get executable file, which we can see readme .

 more: https://github.com/apache/maven-mvnd/issues/512

**Comment by coderYii** [comment]
[Build mvnd](https://github.com/apache/maven-mvnd#build-mvnd)

**Comment by gnodet** [comment]
You need to use the `mvnd` compiled to native instead of `mvnd.sh`, as the java client requires JDK 11.
