### ISSUE TITLE
Exception in thread "main" org.mvndaemon.mvnd.common.DaemonException$ConnectException: Timeout waiting to connect to the  Maven daemon.

### ISSUE THREAD

**Issue by hualr** [apache/maven-mvnd#578]
i cant use mavn-mvnd for the maven daemon can not be connected.why?

**Comment by ppalaga** [comment]
You may want to check the logs in `~/.m2/mvnd/registry/<version>/`.

**Comment by gnodet** [comment]
In addition to the daemon log pointed by @ppalaga , you can enable logging on the client using
```
MAVEN_OPTS="-DconsoleLevel=trace" mvnd.sh -v
```

**Comment by Chris9809** [comment]
Same problem, and log shows
``` java
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.mvndaemon.mvnd.common.MavenDaemon.main(MavenDaemon.java:84)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at org.mvndaemon.mvnd.daemon.Server.<init>(Server.java:121)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.mvndaemon.mvnd.common.MavenDaemon$1.findClass(MavenDaemon.java:69)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

```

**Comment by hualr** [comment]
> Same problem, and log shows
> 
> ```java
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.mvndaemon.mvnd.common.MavenDaemon.main(MavenDaemon.java:84)
> Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
> 	at org.mvndaemon.mvnd.daemon.Server.<init>(Server.java:121)
> 	... 5 more
> Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at org.mvndaemon.mvnd.common.MavenDaemon$1.findClass(MavenDaemon.java:69)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 6 more
> ```

en,show this exception.
