### ISSUE TITLE
No message received within 3000ms, 

### ISSUE THREAD

**Issue by junxin367** [apache/maven-mvnd#584]
at org.mvndaemon.mvnd.client.DaemonClientConnection.receive(DaemonClientConnection.java:129)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:296)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:118)
Caused by: java.io.IOException: No message received within 3000ms, daemon may have crashed. You may want to check its status using mvnd --status
	at org.mvndaemon.mvnd.client.DaemonClientConnection.receive(DaemonClientConnection.java:111)

How do you handle this error?

**Comment by junxin367** [comment]
mvnd.keepAlive = 10000 ms
