### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by gnodet** [apache/maven-mvnd#597]
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.1-SNAPSHOT:process (process-resource-bundles) on project maven-plugin-api: Execution process-resource-bundles of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.1-SNAPSHOT:process failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:274)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:196)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution process-resource-bundles of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.1-SNAPSHOT:process failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:271)
        ... 11 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.apache.maven.RepositoryUtils.getWorkspace(RepositoryUtils.java:376)
        at org.apache.maven.plugin.DefaultPluginArtifactsCache$CacheKey.<init>(DefaultPluginArtifactsCache.java:70)
        at org.apache.maven.plugin.DefaultPluginArtifactsCache.createKey(DefaultPluginArtifactsCache.java:135)
        at org.mvndaemon.mvnd.plugin.CliMavenPluginManager.setupExtensionsRealm(CliMavenPluginManager.java:710)
        at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm(DefaultProjectBuildingHelper.java:197)
        at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultModelBuildingListener.java:101)
        at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatapult.java:44)
        at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:1186)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:436)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:408)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:244)
        at org.apache.maven.project.CachingProjectBuilder.build(CachingProjectBuilder.java:169)
        at org.apache.maven.project.CachingProjectBuilder.build(CachingProjectBuilder.java:312)
        at org.apache.maven.project.CachingProjectBuilder.build(CachingProjectBuilder.java:275)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.getProjects(ProcessRemoteResourcesMojo.java:664)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo$1.internalGet(ProcessRemoteResourcesMojo.java:1043)
        at org.apache.velocity.context.AbstractContext.get(AbstractContext.java:193)
        at org.apache.velocity.context.InternalContextAdapterImpl.get(InternalContextAdapterImpl.java:267)
        at org.apache.velocity.runtime.parser.node.ASTReference.getVariableValue(ASTReference.java:991)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:240)
        at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)
        at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:318)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
        at org.apache.velocity.Template.merge(Template.java:356)
        at org.apache.velocity.Template.merge(Template.java:260)
        at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:354)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.processResourceBundles(ProcessRemoteResourcesMojo.java:1250)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.execute(ProcessRemoteResourcesMojo.java:531)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        ... 12 common frames omitted
```

**Comment by gnodet** [comment]
Can't reproduce.
