### ISSUE TITLE
java.nio.BufferUnderflowException occurs when I run any mvnd command

### ISSUE THREAD

**Issue by jcm007** [apache/maven-mvnd#601]
Hi Experts,

I get this error even when I run mvnd -v:
PS D:\_Projects\Java\xxx> mvnd -v
mvnd native client 0.7.1-windows-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Exception in thread "main" java.nio.BufferUnderflowException
        at java.nio.ByteBuffer.get(ByteBuffer.java:798)
        at java.nio.ByteBuffer.get(ByteBuffer.java:826)
        at org.mvndaemon.mvnd.common.DaemonRegistry.readString(DaemonRegistry.java:303)
        at org.mvndaemon.mvnd.common.DaemonRegistry.doUpdate(DaemonRegistry.java:209)
        at org.mvndaemon.mvnd.common.DaemonRegistry.read(DaemonRegistry.java:164)
        at org.mvndaemon.mvnd.common.DaemonRegistry.getAll(DaemonRegistry.java:102)
        at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:101)
        at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:272)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:118)

When I run other commands, it will be like:
PS D:\_Projects\Java\xxx> mvnd clean install -DskipTests=true '-Dmaven.javadoc.skip=true' '-Dmaven.compile.fork=t
rue' -T 0.8C
Exception in thread "main" java.nio.BufferUnderflowException
        at java.nio.ByteBuffer.get(ByteBuffer.java:798)
        at java.nio.ByteBuffer.get(ByteBuffer.java:826)
        at org.mvndaemon.mvnd.common.DaemonRegistry.readString(DaemonRegistry.java:303)
        at org.mvndaemon.mvnd.common.DaemonRegistry.doUpdate(DaemonRegistry.java:209)
        at org.mvndaemon.mvnd.common.DaemonRegistry.read(DaemonRegistry.java:164)
        at org.mvndaemon.mvnd.common.DaemonRegistry.getAll(DaemonRegistry.java:102)
        at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:101)
        at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:272)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:118)

Please help. Thanks in advance.

**Comment by garywhittington** [comment]
The same problem started for me today.  I resolved it by removing the $HOME/.m2/mvnd directory, and then all seems to be working again (with mvnd then recreating this directory).

**Comment by gnodet** [comment]
Yes, the exception clearly indicates the registry has been corrupted.  We should put some safeguard mechanism to handle this use case more gracefully.  As indicated by @garywhittington, deleting the `$HOME/.m2/mvnd` should be a good workaround.
