### ISSUE TITLE
`mvnd.exe` gives error about DLL

### ISSUE THREAD

**Issue by jglick** [apache/maven-mvnd#607]
I tried downloading https://github.com/apache/maven-mvnd/releases/download/0.7.1/mvnd-0.7.1-windows-amd64.zip and running the contained `mvnd.exe`. This reports an error in a dialog box:

> The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem.

(same from Chocolatey: #160)

Whereas `mvnd.cmd` does not get this error, and `-version` works. Other commands do not:

```
mvnd JVM client 0.7.1-windows-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:196)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:118)
Caused by: java.lang.NumberFormatException: For input string: "self"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at org.mvndaemon.mvnd.common.DaemonRegistry.getProcessId0(DaemonRegistry.java:290)
        at org.mvndaemon.mvnd.common.DaemonRegistry.<clinit>(DaemonRegistry.java:271)
        ... 2 more
```

**Comment by Gaming32** [comment]
Go here and scroll down a little for a fix: https://github.com/apache/maven-mvnd#install-manually.

**Comment by jglick** [comment]
Thanks @Gaming32! That fixes the DLL issue. I filed #608 for the next error.
