### ISSUE TITLE
mvnd on Windows throws `java.lang.NumberFormatException: For input string: "self"`

### ISSUE THREAD

**Issue by jglick** [apache/maven-mvnd#608]
As in #607,

```
mvnd JVM client 0.7.1-windows-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: C:\Program Files\mvndaemon\mvnd-0.7.1-windows-amd64\mvn
Java version: 11.0.13, vendor: Oracle Corporation, runtime: C:\Program Files\OpenJDK\openjdk-11.0.13_8
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

does not seem to work to run builds (anything other than `-version`):

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:196)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:118)
Caused by: java.lang.NumberFormatException: For input string: "self"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at org.mvndaemon.mvnd.common.DaemonRegistry.getProcessId0(DaemonRegistry.java:290)
        at org.mvndaemon.mvnd.common.DaemonRegistry.<clinit>(DaemonRegistry.java:271)
        ... 2 more
```

Seems distinct from #147 / #149.

**Comment by ppalaga** [comment]
We wanted to keep the daemon Java 8 compatible and that's why we avoided getting the PID via standard Java 9+ API `ProcessHandle.current().pid()`. We use `ManagementFactory.getRuntimeMXBean().getName().split("@", 0)[0]` instead, which apparently does not work on your system.

Could you please paste the output of `ManagementFactory.getRuntimeMXBean().getName()` on your machine using the same JDK that mvnd uses? I guess something like the following could work:

```
echo "java.lang.management.ManagementFactory.getRuntimeMXBean().getName()" | C:\Program Files\OpenJDK\openjdk-11.0.13_8\bin\jshell
```

**Comment by jglick** [comment]
That returns `6024@DESKTOP-87…V`. More specifically

```
>echo Integer.parseInt(java.lang.management.ManagementFactory.getRuntimeMXBean().getName().split("@", 0)[0]) | jshell
|  Welcome to JShell -- Version 11.0.13
|  For an introduction type: /help intro

jshell> Integer.parseInt(java.lang.management.ManagementFactory.getRuntimeMXBean().getName().split("@", 0)[0])$1 ==> 6372
```

Yet https://github.com/apache/maven-mvnd/blob/97c587c11383a67b5bd0ff8388bd94c694b91c1e/common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java#L283-L290 fails when run from mvnd.

It is difficult to confirm the JVM being used by `mvnd` because this error crashes it before it gets as far as printing the JVM information. Perhaps noteworthy is that when I run `mvnd` from the `C` drive (where I guess Java is installed; via `choco` so did not pay much attention) I get a different error

```
C:\>mvnd -version
mvnd native client 0.7.1-windows-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Exception in thread "main" java.lang.IllegalStateException: Could not get value for Environment.JAVA_HOME from any of the following sources: value: java.home, environment variable JAVA_HOME, property java.home in C:\Users\…\.mvn\mvnd.properties, property java.home in C:\Users\…\.m2\mvnd.properties, property java.home in C:\Program Files\mvndaemon\mvnd-0.7.1-windows-amd64\conf\mvnd.properties, system property java.home
        at org.mvndaemon.mvnd.client.DaemonParameters$EnvValue.couldNotgetValue(DaemonParameters.java:596)
        at org.mvndaemon.mvnd.client.DaemonParameters$EnvValue.lambda$orFail$8(DaemonParameters.java:573)
        at org.mvndaemon.mvnd.client.DaemonParameters$EnvValue.get(DaemonParameters.java:606)
        at org.mvndaemon.mvnd.client.DaemonParameters$EnvValue.asPath(DaemonParameters.java:629)
        at org.mvndaemon.mvnd.client.DaemonParameters.javaHome(DaemonParameters.java:140)
        at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:99)
        at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:272)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:118)
```

The error from `DaemonRegistry` is only printed when running from another drive, which is mapped to a Linux filesystem. I think the problem is that `\proc\self` _does_ exist but we should not be consulting it. I will try to offer a patch.

**Comment by ppalaga** [comment]
> the problem is that \proc\self does exist but we should not be consulting it. I will try to offer a patch.

Ah, great catch, that's certainly the root cause!
