### ISSUE TITLE
Cannot suppress debug logging as of 0.8.0 on Homebrew on M1 Mac (previous versions didn't have this issue)

### ISSUE THREAD

**Issue by petergeneric** [apache/maven-mvnd#656]
I've installed mvnd 0.8.0 with homebrew, but now I cannot stop mvnd's debug logs from appearing. Here's the result when I run `mvnd --version`:

```
$ mvnd --version
00:58:39.361 [main] DEBUG org.mvndaemon.mvnd.client.DefaultClient - Starting client
                                                                                                                                                      Looking up daemon...  time: 00:00daemon.mvnd.common.DaemonRegistry - loading own PID from VM name: 9326
00:58:39.394 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Found 1 idle daemons, 1 compatibles
00:58:39.394 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Connecting to Daemon
00:58:39.394 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Trying to connect to address /127.0.0.1:51178.
00:58:39.412 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Removing daemon from the registry due to communication failure. Daemon information: DaemonInfo{id=08362c17javaHome=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home, options=[mvnd.home=/opt/homebrew/Cellar/mvnd/0.8.0/libexec, jdk.java.options=--add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED, mvnd.noDaemon=false, mvnd.debug=false, mvnd.idleTimeout=3h, mvnd.keepAlive=100ms, mvnd.extClasspath=, mvnd.coreExtensions=, mvnd.enableAssertions=false, mvnd.expirationCheckDelay=10s, mvnd.duplicateDaemonGracePeriod=10s, mvnd.socketFamily=inet], mavenHome=/opt/homebrew/Cellar/mvnd/0.8.0/libexec, pid=9314, address=inet:/127.0.0.1:51178, locale=en-GB, state=Idle, lastIdle=1653436699910, lastBusy=1653436699647}
00:58:39.412 [main] DEBUG org.mvndaemon.mvnd.common.DaemonRegistry - Storing daemon stop event with timestamp 1653436719412
00:58:39.413 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Connected
00:58:39.414 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Cannot connect to daemon DaemonInfo{id=08362c17javaHome=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home, options=[mvnd.home=/opt/homebrew/Cellar/mvnd/0.8.0/libexec, jdk.java.options=--add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED, mvnd.noDaemon=false, mvnd.debug=false, mvnd.idleTimeout=3h, mvnd.keepAlive=100ms, mvnd.extClasspath=, mvnd.coreExtensions=, mvnd.enableAssertions=false, mvnd.expirationCheckDelay=10s, mvnd.duplicateDaemonGracePeriod=10s, mvnd.socketFamily=inet], mavenHome=/opt/homebrew/Cellar/mvnd/0.8.0/libexec, pid=9314, address=inet:/127.0.0.1:51178, locale=en-GB, state=Idle, lastIdle=1653436699910, lastBusy=1653436699647} due to {}. Trying a different daemon...
org.mvndaemon.mvnd.common.DaemonException$ConnectException: Could not connect to server /127.0.0.1:51178.
	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:517)
	at org.mvndaemon.mvnd.client.DaemonConnector.connectToDaemon(DaemonConnector.java:446)
	at org.mvndaemon.mvnd.client.DaemonConnector.findConnection(DaemonConnector.java:274)
	at org.mvndaemon.mvnd.client.DaemonConnector.connectToIdleDaemon(DaemonConnector.java:229)
	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:106)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:284)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:129)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:488)
	... 6 common frames omitted
00:58:39.418 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Found 0 busy daemons, 0 cancelled, 0 compatibles
00:58:39.418 [main] DEBUG org.mvndaemon.mvnd.common.DaemonRegistry - Removing 0 daemon stop events from registry
00:58:39.420 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Previous Daemon (61cb9247) stopped at 1653436699081 by user or operating system
00:58:39.420 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Previous Daemon (c92811dc) stopped at 1653436367512 by user or operating system
Starting new daemon 9a337184, 1 incompatible and 3 stopped daemons could not be reused, use --status for details  time: 00:00stem
00:58:39.428 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Starting daemon process: id = 9a337184, workingDir = /private/tmp, daemonArgs: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/java -classpath /opt/homebrew/Cellar/mvnd/0.8.0/libexec/mvn/lib/ext/mvnd-common-0.8.0.jar:/opt/homebrew/Cellar/mvnd/0.8.0/libexec/mvn/lib/ext/mvnd-agent-0.8.0.jar -javaagent:/opt/homebrew/Cellar/mvnd/0.8.0/libexec/mvn/lib/ext/mvnd-agent-0.8.0.jar -Dmvnd.home=/opt/homebrew/Cellar/mvnd/0.8.0/libexec -Dmaven.home=/opt/homebrew/Cellar/mvnd/0.8.0/libexec/mvn -Dmaven.conf=/opt/homebrew/Cellar/mvnd/0.8.0/libexec/mvn/conf -Dmvnd.java.home=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home -Dlogback.configurationFile=/opt/homebrew/Cellar/mvnd/0.8.0/libexec/conf/logback.xml -Dmvnd.id=9a337184 -Dmvnd.daemonStorage=/Users/user/.m2/mvnd/registry/0.8.0 -Dmvnd.registry=/Users/user/.m2/mvnd/registry/0.8.0/registry.bin -Dmvnd.socketFamily=inet -Dmvnd.home=/opt/homebrew/Cellar/mvnd/0.8.0/libexec -Djdk.java.options=--add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Dmvnd.noDaemon=false -Dmvnd.debug=false -Dmvnd.idleTimeout=3h -Dmvnd.keepAlive=100ms -Dmvnd.extClasspath= -Dmvnd.coreExtensions= -Dmvnd.enableAssertions=false -Dmvnd.expirationCheckDelay=10s -Dmvnd.duplicateDaemonGracePeriod=10s -Dmvnd.socketFamily=inet org.mvndaemon.mvnd.common.MavenDaemon
00:58:39.435 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Started Maven daemon 9a337184
00:58:40.048 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Connecting to Daemon
00:58:40.049 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Trying to connect to address /127.0.0.1:51194.
00:58:40.062 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Connected to address /127.0.0.1:51194.
00:58:40.062 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Exchanged token successfully
00:58:40.066 [main] DEBUG org.mvndaemon.mvnd.client.DaemonConnector - Connected
00:58:40.066 [main] DEBUG org.mvndaemon.mvnd.client.DaemonClientConnection - thread 1: dispatching class org.mvndaemon.mvnd.common.Message$BuildReques
mvnd 0.8.0 JVM client (2cfffe23eebac7a0fddecf0268478ae963a8859f)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.osx.OsXNativePty
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/homebrew/Cellar/mvnd/0.8.0/libexec/mvn
Java version: 17.0.3, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.4", arch: "aarch64", family: "mac"
00:58:40.178 [main] DEBUG org.mvndaemon.mvnd.client.DaemonClientConnection - thread 1: connection stop
```

I have reinstalled mvnd. I've checked there are no aliases for mvnd, and no custom `~/.m2/mvnd.properties`

Homebrew reports:
```
$ brew info mvnd
mvndaemon/mvnd/mvnd: stable 0.8.0
Maven Daemon
https://github.com/mvndaemon/mvnd
/opt/homebrew/Cellar/mvnd/0.8.0 (95 files, 12.5MB) *
  Built from source on 2022-05-25 at 00:52:13
From: https://github.com/mvndaemon/homebrew-mvnd/blob/HEAD/Formula/mvnd.rb
```

**Comment by electrum** [comment]
I'm seeing this as well on a new M1 Mac after doing a brand new install of Homebrew. I didn't see this on my previous M1 Mac.

**Comment by davsclaus** [comment]
I noticed this too on my M1. I have not tired on an intel, but maybe its a general problem?

**Comment by gnodet** [comment]
This may be due to the fact that there's no native build for osx/aarch64, so that the java client is used.  I'll have a look next week.

**Comment by odrotbohm** [comment]
This is marked as completed but no changes have been committed for this? Does that mean it's rather a user issue? Just asking as I face this, too.

**Comment by electrum** [comment]
It's fixed but we're waiting on a release of mvnd that includes the fix.

**Comment by odrotbohm** [comment]
@gnodet commented on June 18th, he'd be looking into it, and the only commits I see after that seem unrelated. Do you say a previous commit already fixed that?

**Comment by electrum** [comment]
I’m assuming it is https://github.com/apache/maven-mvnd/commit/b3aeb8899ad160e3121fa7786cc1b656fb29bda6

**Comment by odrotbohm** [comment]
Ahhh, great find! Thanks! Looking forward to the release!
