### ISSUE TITLE
mvnd incompatible with Gradle Enterprise's build-scan extension

### ISSUE THREAD

**Issue by seanf** [apache/maven-mvnd#725]
The `gradle-enterprise-maven-extension` (version 1.15.4) works with Maven 3.8.6, but reports "MavenPluginManager was not overridden" when run via `mvnd`.

```
❯ mvnd initialize
[WARN] Failed to initialize spy com.gradle.maven.internal.GradleEnterpriseLifecycleManager: build operation notification valve already started
[INFO] Processing build on daemon c31a048e
[ERROR] Internal error: java.lang.IllegalStateException: MavenPluginManager was not overridden -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalStateException: MavenPluginManager was not overridden
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:687)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:239)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:215)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:572)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:256)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:224)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalStateException: MavenPluginManager was not overridden
	at com.gradle.enterprise.b.a.a(SourceFile:146)
	at com.gradle.enterprise.b.a.a(SourceFile:39)
	at com.gradle.maven.internal.GradleEnterpriseLifecycleManager.afterSessionStart(SourceFile:138)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:208)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	... 7 common frames omitted
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

See example project here: https://github.com/seanf/gradle-enterprise-maven-extension-mvnd-bug

**Comment by gzm55** [comment]
the binding of MavenPluginManager is fixed in the [code](https://github.com/apache/maven-mvnd/blob/0288988d6354053976c00f6d3297ce3bc747e3ab/daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java#L526)

**Comment by marcphilipp** [comment]
The Gradle team is currently working on making the extension compatible with the Maven daemon. So far we haven't hit any road blocks.

**Comment by gnodet** [comment]
Closing this issue, as this seems to have been fixed at some point.
