### ISSUE TITLE
build static native image for linux amd64 system

### ISSUE THREAD

**Issue by gzm55** [apache/maven-mvnd#727]
[Static native image](https://www.graalvm.org/22.3/reference-manual/native-image/guides/build-static-executables/) improves the portability between different libc types (glibc or musl) and glibc versions on x64 linux.

**Comment by gnodet** [comment]
Sounds good. 
This will need to be integrated into https://github.com/apache/maven-mvnd/blob/master/.github/workflows/release.yaml
Not sure about the cost of building musl during the GitHub release workflow though...

**Comment by ppalaga** [comment]
Indeed, this would be nice! 

@gzm55 do you happen to know how much bigger will the native executable become?

**Comment by gzm55** [comment]
> Indeed, this would be nice!
> 
> @gzm55 do you happen to know how much bigger will the native executable become?

not yet, i will try it at weekend

**Comment by gzm55** [comment]
the preparation of the tool chains are less than 1 minutes, and the increasement of the  image sizes can be ignored, less than 1%.

The problem is that the embedded JNIs still depends on glibc:

```bash
$ maven-mvnd-0.9.0-SNAPSHOT-linux-amd64/bin/mvnd --status
Failed to load native library:jansi-2.4.0-df4a30a9a564804a-libjansi.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: Can't load library: /tmp/jansi-2.4.0-df4a30a9a564804a-libjansi.so
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.CLibrary.isatty(I)I [symbol: Java_org_fusesource_jansi_internal_CLibrary_isatty or Java_org_fusesource_jansi_internal_CLibrary_isatty__I]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:53)
        at org.fusesource.jansi.internal.CLibrary.isatty(CLibrary.java)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:95)

```
