### ISSUE TITLE
NullPointerException while running 

### ISSUE THREAD

**Issue by ohavlicek** [apache/maven-mvnd#746]
Hi, I wanted to give this a try, but I'm getting a NPE.

```
[ERROR] NullPointerException
java.lang.NullPointerException: null
        at org.mvndaemon.mvnd.builder.ProjectComparator.create0(ProjectComparator.java:66)
        at org.mvndaemon.mvnd.builder.ProjectComparator.create(ProjectComparator.java:55)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.<init>(SmartBuilderImpl.java:74)
        at org.mvndaemon.mvnd.builder.SmartBuilder.build(SmartBuilder.java:111)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:687)
        at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:239)
        at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:215)
        at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:572)
        at org.mvndaemon.mvnd.daemon.Server.client(Server.java:256)
        at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:224)
        at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]
```

Is there something I can do? 

```
mvnd --version
mvnd 0.8.2 windows-amd64 native client (2bba2d6a4d3a5012ddf9f1f42a22784cad4011e3)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\DiskD\DEV_HOME\TOOLS\maven-mvnd-0.8.2\mvn
Java version: 11.0.6, vendor: Oracle Corporation, runtime: D:\DEV_HOME\TOOLS\java\1.11.0_6
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by ppalaga** [comment]
Could you please provide a reproducer project?
