### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by IvanSmurygin** [apache/maven-mvnd#759]
Hello! I use mvnd with some multimodule project (around 30 dependent modules), during the build the next exception is thrown

```
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:687)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:239)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:215)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:572)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:256)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:224)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at com.gradle.maven.a.a.c.h.a(SourceFile:86)
	at com.gradle.maven.internal.GradleEnterpriseLifecycleManager.afterSessionEnd(SourceFile:137)
	at org.apache.maven.DefaultMaven.afterSessionEnd(DefaultMaven.java:354)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	... 7 common frames omitted
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

```
mvnd -version
mvnd 0.8.2 darwin-amd64 native client (2bba2d6a4d3a5012ddf9f1f42a22784cad4011e3)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.osx.OsXNativePty
[WARN] Failed to initialize spy com.gradle.maven.internal.GradleEnterpriseLifecycleManager: build operation notification valve already started
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /usr/local/Cellar/mvnd/0.8.2/libexec/mvn
Java version: 11.0.16.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@11/11.0.16.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.2", arch: "x86_64", family: "mac"
```

**Comment by mthmulders** [comment]
@marcphilipp, could this be an issue in the Gradle Enterprise Maven extension? In #725, I saw you posted a note that the Gradle team is currently working on making the extension compatible with the Maven Daemon.

**Comment by marcphilipp** [comment]
Yes, the Gradle Enterprise Maven extension is not yet compatible with the Maven Daemon but we're working on it and there should soon be a compatible release.

**Comment by gnodet** [comment]
I'm going to close that one, as this is the responsibility of the Gradle extension's team.
