### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Ixf1nity** [apache/maven-mvnd#781]
```C:\Users\Hp\.jdks\corretto-17.0.4\bin>mvnd
Exception in thread "main" java.lang.IllegalStateException: Could not get value for Environment.JAVA_HOME from any of the following sources: value: java.home, property java.home in C:\Users\Hp\.jdks\corretto-17.0.4\bin\.mvn\mvnd.properties, property java.home in C:\Users\Hp\.m2\mvnd.properties, property java.home in C:\Program Files\mvndaemon\maven-mvnd-0.8.2-windows-amd64\conf\mvnd.properties, system property java.home, environment variable JAVA_HOME
        at org.mvndaemon.mvnd.client.DaemonParameters$EnvValue.couldNotgetValue(DaemonParameters.java:615)
        at org.mvndaemon.mvnd.client.DaemonParameters$EnvValue.lambda$orFail$8(DaemonParameters.java:592)
        at org.mvndaemon.mvnd.client.DaemonParameters$EnvValue.get(DaemonParameters.java:625)
        at org.mvndaemon.mvnd.client.DaemonParameters$EnvValue.asPath(DaemonParameters.java:648)
        at org.mvndaemon.mvnd.client.DaemonParameters.javaHome(DaemonParameters.java:141)
        at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:98)
        at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:310)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:144)```

Please help me.

**Comment by gnodet** [comment]
You need to set the `JAVA_HOME` environment variable before launching `mvnd`.
This has been enhanced and now `mvnd` can also discover the `JAVA_HOME` by running the `java` command.
