### ISSUE TITLE
Cannot run program "infocmp"

### ISSUE THREAD

**Issue by lppedd** [apache/maven-mvnd#782]
This seems to a common issue on Windows.
See https://github.com/ctongfei/progressbar/issues/55

Binary used:
```
maven-mvnd-1.0.0-m1-windows-amd64.zip
```

Complete error:
```
C:\Users\edoardo.luppi>mvnd --version
Jan 30, 2023 10:07:19 AM org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type msys
java.io.IOException: Cannot run program "infocmp": CreateProcess error=2, The system cannot find the file specified
        at java.base@17.0.5/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base@17.0.5/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:547)
        at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:204)
        at org.jline.terminal.impl.AbstractWindowsTerminal.<init>(AbstractWindowsTerminal.java:91)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.<init>(JansiWinSysTerminal.java:100)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.createTerminal(JansiWinSysTerminal.java:76)
        at org.jline.terminal.impl.jansi.JansiSupportImpl.winSysTerminal(JansiSupportImpl.java:126)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:348)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:271)
        at org.mvndaemon.mvnd.common.logging.TerminalOutput.<init>(TerminalOutput.java:165)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:150)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:882)
        at java.base@17.0.5/java.lang.ProcessImpl.create(ProcessImpl.java)
        at java.base@17.0.5/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
        at java.base@17.0.5/java.lang.ProcessImpl.start(ProcessImpl.java:158)
        at java.base@17.0.5/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 11 more

mvnd 1.0.0-m1 windows-amd64 native client (7586cf2b0cdd3b57238fa70802affb7a4e6f602f)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 4.0.0-alpha-3 (2ccf57baa5191468f9911fe85fd99672ac3bacb9)
Maven home: C:\Users\edoardo.luppi\Downloads\maven-mvnd-1.0.0-m1-windows-amd64\maven-mvnd-1.0.0-m1-windows-amd64\mvn
Java version: 17.0.4.1, vendor: Amazon.com Inc., runtime: C:\Users\edoardo.luppi\Documents\management\jvms_v2.1.1_amd64\store\corretto-17.0.4.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by lppedd** [comment]
Not sure if this is related to the Deamon or to Maven itself tho.

**Comment by gnodet** [comment]
This is clearly a [jline](https://github.com/jline/jline3) issue.

**Comment by lppedd** [comment]
@gnodet should I move the issue on the jline repo?

**Comment by gnodet** [comment]
> @gnodet should I move the issue on the jline repo?

Yes please.
