### ISSUE TITLE
NPE in daemon prompter when using iteractive mode with no project (using archetype)

### ISSUE THREAD

**Issue by rmannibucau** [apache/maven-mvnd#807]
Here is the stack

```
$ mvn archetype:generate -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] BuildTimeEventSpy is registered.
[INFO] 
[INFO] -------------------------------------------< org.apache.maven:standalone-pom >--------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ---------------------------------------------------------[ pom ]----------------------------------------------------------
[INFO] 
[INFO] --- archetype:3.2.0:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [org.apache.maven.archetypes:maven-archetype-quickstart:1.4] found in catalog remote
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] --------------------------------------------------------------------------------------------------------------------------
[INFO] Total time:  1.860 s
[INFO] Finished at: 2023-03-10T10:00:51+01:00
[INFO] --------------------------------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: Failed to prompt user: Unable to prompt user: NullPointerException -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: Failed to prompt user
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:341)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:324)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:77)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:114)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:60)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:132)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:313)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:228)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:859)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:282)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:198)
...
Caused by: java.io.IOException: Unable to prompt user
	at org.mvndaemon.mvnd.interactivity.DaemonPrompter.doPrompt(DaemonPrompter.java:175)
	at org.mvndaemon.mvnd.interactivity.DaemonPrompter.doPrompt(DaemonPrompter.java:111)
	... 32 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at org.mvndaemon.mvnd.interactivity.DaemonPrompter.doPrompt(DaemonPrompter.java:166)
	... 33 common frames omitted
```

**Comment by psiroky** [comment]
Which version of `mvnd` are you seeing this with? I tried with `0.9.0` and the latest master (ca4bdd03b3fdec7ee7f67b787a764b2ddb8d8043), but could not reproduce.

That being said, `DaemonPrompter.java:166` contains `Connection con = Objects.requireNonNull(Connection.getCurrent());` which seems like the the connection got lost for some reason? But then I am not sure how would the error message / stacktrace got to the client.

**Comment by gnodet** [comment]
> Which version of `mvnd` are you seeing this with? I tried with `0.9.0` and the latest master ([ca4bdd0](https://github.com/apache/maven-mvnd/commit/ca4bdd03b3fdec7ee7f67b787a764b2ddb8d8043)), but could not reproduce.
> 
> That being said, `DaemonPrompter.java:166` contains `Connection con = Objects.requireNonNull(Connection.getCurrent());` which seems like the the connection got lost for some reason? But then I am not sure how would the error message / stacktrace got to the client.

I think that's using the `mvn` script from `mvnd`, that's why there's no connection...

**Comment by rmannibucau** [comment]
Think the option to have a mvn.m2.conf and a mvnd.m2.conf is very tempting.

**Comment by gnodet** [comment]
> Think the option to have a mvn.m2.conf and a mvnd.m2.conf is very tempting.

We already have 3 configs in the master: one for `maven`, one for the _mvnd client_ and one for the _mvnd daemon_.  So it's just a matter of modifying the distribution / config so that the daemon jars are not included when starting maven.
