### ISSUE TITLE
`Could not acquire write lock for…` errors

### ISSUE THREAD

**Issue by jglick** [apache/maven-mvnd#836]
I just upgraded mvnd to 1.0-m6-m39 via Snap from 0.9.0 (using Java 11) and ran a build of my reactor with 27 modules as usual (max parallelism 11). It spat out some errors such as

```
Could not acquire write lock for '~/.m2/repository/.locks/com.github.spotbugs~spotbugs-annotations~4.7.3.lock'
Could not acquire write lock for '~/.m2/repository/.locks/commons-collections~commons-collections~3.2.2.lock'
```

and the build failed partway through

```
Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (enforce-bytecode-version) on project …: Execution enforce-bytecode-version of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce failed: Could not acquire write lock for '~/.m2/repository/.locks/groupId~artifactId~1.234.lock' -> [Help 1]
Failed to execute goal some:plugin:1.2:some-mojo (default-some-mojo) on project …: Execution default-some-mojo of goal some:plugin:1.2:some-mojo failed: Could not acquire write lock for '~/.m2/repository/.locks/groupId2~artifactId2~5.678.lock' -> [Help 1]
Could not acquire write lock for '~/.m2/repository/.locks/groupId3~artifactId3~9.012.lock'
```

When I ran the build again, it passes, so I presume this was some sort of race condition, possibly involving artifact downloads (I had pulled in various POM updates since the last local build of the project).

No further details were provided, and I was not using `-e` so there was no stack trace giving context. I checked `~/.m2/mvnd/registry/1.0-m6/daemon-*.log` which did not really add any more information:

```
Dispatch message: ExecutionFailure{projectId='…', halted=true, exception='java.lang.IllegalStateException: Could not acquire write lock for '~/.m2/repository/.locks/com.github.spotbugs~spotbugs-annotations~4.7.3.lock''}
```

If nothing else, the `Throwable.toString` of the cause ought to be included in the top-level error message I think.

**Comment by sinyagin** [comment]
Faced the same issue on 1.0-m7 windows version. 
`Apache Maven Daemon (mvnd) 1.0-m7 windows-amd64 native client (b2ef5d81997adbcdb72dc8c5603722538fa641fe)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 4.0.0-alpha-7 (bf699a388cc04b8e4088226ba09a403b68de6b7b)
Maven home: C:\work\tools\mvnd-0.7.1-windows-amd64\mvn
Java version: 11.0.15, vendor: Eclipse Adoptium, runtime: C:\work\tools\java\jdk-11.0.15.10-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"` 
I was able to get a full stack trace 
` Suppressed: java.lang.IllegalStateException: Attempt 1: Could not acquire write lock for 'C:\work\repository\.locks\artifact~antlr~antlr~2.7.6.lock' in 30 SECONDS
        at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire (NamedLockFactoryAdapter.java:202)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:271)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:259)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:352)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:187)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:242)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectArtifacts (LifecycleDependencyResolver.java:193)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:131)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:361)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:318)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:178)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:77)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:166)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:114)
        at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:209)
        at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
        at java.util.concurrent.FutureTask.run (FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
        at java.lang.Thread.run (Thread.java:829)`

**Comment by gnodet** [comment]
@cstamas any idea ?

**Comment by eliasbalasis** [comment]
FYI.

I have discovered that there is probably some problem with the Maven resolver implementation.

I initially used apache-maven-3.8.8-resolver-1.9.7 but neither [Redisson](https://maven.apache.org/resolver/maven-resolver-named-locks-redisson/index.html) nor [Hazelcast](https://maven.apache.org/resolver/maven-resolver-named-locks-hazelcast/index.html) worked.
Now I am using apache-maven-3.8.8-resolver-1.8.2 and [Redisson](https://maven.apache.org/resolver/maven-resolver-named-locks-redisson/index.html) works but [Hazelcast](https://maven.apache.org/resolver/maven-resolver-named-locks-hazelcast/index.html) still doesn't work.

I am guessing this will be all eventually fixed in Maven 3.9 as soon as it matures first.

**Comment by hohwille** [comment]
```
$ mvnd -v
Apache Maven Daemon (mvnd) 1.0-m7 windows-amd64 native client (b2ef5d81997adbcdb72dc8c5603722538fa641fe)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)
Maven home: D:\projects\salog\software\mvnd\mvn
Java version: 17.0.8, vendor: Eclipse Adoptium, runtime: D:\projects\salog\software\java
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

But I also get this:
```
Suppressed: java.lang.IllegalStateException: Attempt 1: Could not acquire write lock for 'C:\Users\hohwille\.m2\repository\.locks\artifact~com.caucho~com.springsource.com.caucho~3.2.1.lock' in 30 SECONDS
        at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire (NamedLockFactoryAdapter.java:202)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:271)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:259)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:352)
```

Windows Filesystem and file-locking is a disaster. However, with regular `mvn` the error does not occur even not when I run parallel builds (e.g. `-T 2C`). Please also note that also with `mvnd` the error goes away if I do not specify concurrent build (no `-T` option).

**Comment by eliasbalasis** [comment]
> Windows Filesystem and file-locking is a disaster

I couldn't agree more.

> the error does not occur even not when I run parallel builds

Trust me, it is purely non-deterministic, I thought the same at first.
Even Named Locks don't seem to be working perfectly yet.
"-Daether.connector.basic.threads=1 -Daether.connector.resumeDownloads=false" hasn't worked perfectly either.
From where I stand, this is a dead end at the moment.
My hopes lie with Maven 3.9

**Comment by hohwille** [comment]
I was now able to reproduce the lock errors also with pure maven and without mvnd.
Therefore I created [MNG-7868](https://issues.apache.org/jira/browse/MNG-7868).
IMHO this issue here is kind of invalid as it is a bug in maven itself and not in mvnd.

**Comment by cstamas** [comment]
Locking in Mavem aims to solve two things:
* parallel build coordination (within one Maven parallel building process)
* shared local repository across several Maven (ST or MT, parallel) processes

For brevity we call them 
* ST,  single threaded, the "usual" way of Maven working, 
* MT, multi threaded, or "parallel", either using `-T` with or without "smart builder"/mvnd and 
* MP, multi process case, when local repository is shared across multiple Maven ST/MT processes (on single or multiple hosts).

HOW locking is set up (especially for which scenario, MT/MP) is left to user, some examples:
* the default locking (since 3.9.0) the `rwlock-local` as name says is (JVM) local, so handles only MT builds
* the `file-lock` can handle MP cases (on single host, or on properly set up NFS volume)
* for larger scale, usually CI use case with shared local repositories, we recommend the Hazelcast/Redisson solutions

By the way, for non-mvnd users I'd personally recommend to NOT use the "vanilla" `-T` builder (that comes with Maven), but rather use the superior Takari Smart Builder (see [README](https://github.com/takari/takari-smart-builder/blob/master/README.md)). This will make Maven parallel builds behave similarly as mvnd (also uses Smart builder) sans the persistent daemon and logging feature.

I would really like to see a reproducer project that produces this kind of error, but let me explain what happens here...

By default, the parameter `aether.syncContext.named.time` (30 seconds) is the amount of time a synchronization context shall wait to obtain a needed lock. In latest Maven/mvnd releases the message is actually improved to clearly show that (as can be seen above in comments, but not in original issue description: "Could not acquire write lock for $lockName in 30 SECONDS"). So, there is no cause per se, the cause IS the timeout.

Sadly, way before NamedLocks (that are actually used as "low level fine grained locking implementation") the [`SyncContext`](https://github.com/apache/maven-resolver/blob/maven-resolver-1.9.15/maven-resolver-api/src/main/java/org/eclipse/aether/SyncContext.java) was defined way earlier and I "inherited" it. Major problem with this API is "coarseness" of it. 

My current assumption/focus is "hot artifacts": artifacts that are highly referenced (for example like slf4j-api might be in a project, or some "api" module that has zillion downstream plugin modules building against given api module, etc -- usually "star shaped" projects at least when dependencies observed) due `SyncContext` above could cause that parallel resolved module dependencies became serially resolved, and -- especially on larger projects -- the "looser" threads end up congested, waiting more then 30 seconds, that will cause the timeout.

Current (bad) workaround for this is raising the time limit using `-Daether.syncContext.named.time=40` (default time unit is seconds) and "experiment", as this value theoretically depends on project layout and size. But is bad, as you want fast builds, but this actually slows it down even more.

---

An example of perf test against Apache Camel is here: https://cstamas.github.io/camel-perftest/
Sadly, I could not make it perform these errors.

---

So any (hopefully OSS) "reproducer project" is welcome, to sort out last bits of Maven locking. TIA!

**Comment by eliasbalasis** [comment]
This is a very good direction.

I have witnessed locking failures on larger projects even with Redisson and Hazelcast (as mentioned in the past).
These are probably timeouts in which case the plain error message I am getting `Could not acquire write lock for ...` is badly worded.
However, it seems I missed the error detail .
`Could not acquire write lock for 'C:\work\repository\.locks\artifact~antlr~antlr~2.7.6.lock' in 30 SECONDS`
which explains the problem.

I will increase the time limit using `-Daether.syncContext.named.time` and get back to you.

**Comment by cstamas** [comment]
> IMHO this issue here is kind of invalid as it is a bug in maven itself and not in mvnd.

I agree with this assesment, and is perfectly clear: mvnd only suffers from this bug (as it pressures the locking most), that is actually deep in resolver.

**Comment by cstamas** [comment]
And one more note: with latest Maven 3.9.4 you have option to collect "diagnostic data" for locking as well, and in case of those timeouts, it will spit out the diag data, see here https://maven.apache.org/resolver/maven-resolver-named-locks/index.html#diagnostic-collection-in-case-of-failures

Note: collecting diag data has impact on heap usage, so you may need to tweak it, if you hit OOM.

**Comment by eliasbalasis** [comment]
Noted, the disgnostics work only with Maven 3.9.4 and resolver 1.9.14+

However, the timeout change didn't work:
using `-Daether.syncContext.named.factory=semaphore-hazelcast -Daether.syncContext.named.nameMapper=gav -Daether.syncContext.named.time=60`
SmartBuilder and Maven 3.8.8-resolver-1.8.2
I am still getting the same errors:

```
12:53:38.601 E Internal error: java.lang.IllegalStateException: Could not acquire write lock for 'artifact:XXX' -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalStateException: Could not acquire write lock for 'artifact:XXX'
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:963)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:296)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.IllegalStateException: Could not acquire write lock for 'artifact:XXX'
    at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire(NamedLockFactoryAdapter.java:165)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:233)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:272)
    at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:192)
    at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:242)
    at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1150)
    at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:916)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:361)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:267)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:448)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:414)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:377)
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:414)
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:405)
    at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:82)
    at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:535)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:220)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    ... 11 common frames omitted
```

Should I wait for opportunity to run with Maven 3.9.x ? or am I missing something?

**Comment by cstamas** [comment]
Sorry, all this above is true for Maven 3.9.4 and latest 1.9.14+ resolver... 
Am really unsure what Maven 3.8.8-resolver-1.8.2 is.... Is it @michael-o product? https://maven.apache.org/resolver/maven-3.8.x.html

What stops you to move to Maven 3.9.4?

**Comment by eliasbalasis** [comment]
Nothing stops us, besides workload, commitments and priorities.

I have planned for this to happen later this year.

**Comment by michael-o** [comment]
@cstamas @eliasbalasis Re: Maven 3.8.x with Resolver 1.9.x: Yes, I do produce and sign those deliverables. Cherry-picked commits allowing people access new Resolver if thy can't/want/whatever upgrade. I will upgade those to 1.9.15 shortly.

**Comment by guw** [comment]
@cstamas We are using Apache Resolver 1.9.13 in a different project and started to see the locking issues as well. Can it be related to a slow file system? When was this locking introduced? Given that this is outside of `mvnd` should the issue be moved to the Maven Resolver project?

```
java.lang.IllegalStateException: Could not acquire lock(s)
        at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire(NamedLockFactoryAdapter.java:219)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:271)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:259)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:242)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:231)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:172)
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.resolveCachedArtifactDescriptor(DfDependencyCollector.java:382)
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.getArtifactDescriptorResult(DfDependencyCollector.java:368)
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:218)
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.processDependency(DfDependencyCollector.java:156)
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.process(DfDependencyCollector.java:138)
        at org.eclipse.aether.internal.impl.collect.df.DfDependencyCollector.doCollectDependencies(DfDependencyCollector.java:108)
        at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:222)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:327)
        at ...
        Suppressed: java.lang.IllegalStateException: Attempt 1: Could not acquire write lock for 'artifact:junit:junit:4.13.2' in 30 SECONDS
                at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire(NamedLockFactoryAdapter.java:202)
                ... 30 more
        Suppressed: java.lang.IllegalStateException: Attempt 2: Could not acquire write lock for 'artifact:junit:junit:4.13.2' in 30 SECONDS
                at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire(NamedLockFactoryAdapter.java:202)
                ... 30 more
```

**Comment by cstamas** [comment]
@guw this is definitely maven-resolver issue, but cannot say more without knowing more. Please try to enable "lock diag" (set *system property* --not Maven property!) `aether.named.diagnostic.enabled=true`.

**Comment by eliasbalasis** [comment]
> @cstamas @eliasbalasis Re: Maven 3.8.x with Resolver 1.9.x: Yes, I do produce and sign those deliverables. Cherry-picked commits allowing people access new Resolver if thy can't/want/whatever upgrade. I will upgade those to 1.9.15 shortly.

@michael-o
Did you have any opportunity to publish the latest version of "Resolver" ?



> @guw this is definitely maven-resolver issue, but cannot say more without knowing more. Please try to enable "lock diag" (set _Java system property_ --not Maven property!) `aether.named.diagnostic.enabled=true`.
> 
> Edit: locking was introduced in Resolver 1.8.x but reworked/generalized in 1.9.x lineage.

It is with Java system property that I experimented but I never got any detailed output.

Also as @cstamas mentioned further up:
> And one more note: with latest Maven 3.9.4 you have option to collect "diagnostic data" for locking as well, and in case of those timeouts, it will spit out the diag data, see here https://maven.apache.org/resolver/maven-resolver-named-locks/index.html#diagnostic-collection-in-case-of-failures
> 
> ...
> ...
> 
> Big fat note: use it ONLY with Maven 3.9.4 (actually, with resolver 1.9.14+), as before, it emitted WRONG data (see [MRESOLVER-380](https://issues.apache.org/jira/browse/MRESOLVER-380)). This means mvnd is out of scope, as latest m7 uses older resolver....

It seems Maven 3.9.x is the only effective way.
However, I do vaguely recall having tried Maven 3.9.x at some point discovering some incompatibilities that I didn't have the time to explore, which may be implying that we are at a dead end.
I have planned for an upgrade to Maven 3.9.x before the ned of this year, at which point I am expecting to stumble upon any incompatibilities and I will let you know.

**Comment by michael-o** [comment]
> > @cstamas @eliasbalasis Re: Maven 3.8.x with Resolver 1.9.x: Yes, I do produce and sign those deliverables. Cherry-picked commits allowing people access new Resolver if thy can't/want/whatever upgrade. I will upgade those to 1.9.15 shortly.
> 
> @michael-o Did you have any opportunity to publish the latest version of "Resolver" ?
> 
> > @guw this is definitely maven-resolver issue, but cannot say more without knowing more. Please try to enable "lock diag" (set _Java system property_ --not Maven property!) `aether.named.diagnostic.enabled=true`.
> > Edit: locking was introduced in Resolver 1.8.x but reworked/generalized in 1.9.x lineage.
> 
> @guw It is with Java system property that I experimented but I never got any detailed output (using https://maven.apache.org/resolver/maven-3.8.x.html)
> 
> Also as @cstamas mentioned further up:
> 
> > And one more note: with latest Maven 3.9.4 you have option to collect "diagnostic data" for locking as well, and in case of those timeouts, it will spit out the diag data, see here https://maven.apache.org/resolver/maven-resolver-named-locks/index.html#diagnostic-collection-in-case-of-failures
> > ...
> > ...
> > Big fat note: use it ONLY with Maven 3.9.4 (actually, with resolver 1.9.14+), as before, it emitted WRONG data (see [MRESOLVER-380](https://issues.apache.org/jira/browse/MRESOLVER-380)). This means mvnd is out of scope, as latest m7 uses older resolver....
> 
> It seems Maven 3.9.x is the only effective way. However, I do vaguely recall having tried Maven 3.9.x at some point discovering some incompatibilities that I didn't have the time to explore, which may be implying that we are at a dead end. I have planned for an upgrade to Maven 3.9.x before the ned of this year, at which point I am expecting to stumble upon any incompatibilities and I will let you know.
> 
> This is not "mvnd" related though, without a shadow of a doubt. Should we post this somewhere else?

Planning to package today.

**Comment by michael-o** [comment]
@eliasbalasis Distros delivered. Please check them out from the dist dev space.

**Comment by eliasbalasis** [comment]
@michael-o
many thanks for making the effort, it helps a lot.

I will try it and see how it goes.

**Comment by cstamas** [comment]
@eliasbalasis could you please provide us feedback why did official 3.9.x release not work for you? I think the real path should be forward, instead to stick to one-man && non-asf maven customized distribution (that as example shows above, just makes things worse, as both users and devs are confused why things does not work while they should [IF it would be official distro])...

**Comment by eliasbalasis** [comment]
@cstamas
I agree with moving forward but I hope you understand that such transformations often have a cost that has to be prioritized, particularly when the relevant systems are used by multiple teams on multiple projects to eliminate disruption of any operations.

That said, I do recall having tried running some of our builds on Mavel 3.9.x as an experiment in the past but I cannot remember off the top of my head the exact errors.

However, like I said, I have planned for this transformation to happen before the end of this year, as part of our yearly technical debt handling effort, at which point I will know the exact problem and I will report it, if it is still effective.

**Comment by eliasbalasis** [comment]
As promised, I am now transforming our build systems to make use of Maven 3.9.6 and named locks for our parallel builds.

The first indications are promising, using a remote Redisson cache.
However, it will take a while to observe the system under heavy load.

I will be reporting findings here.

**Comment by eliasbalasis** [comment]
Unfortunately, after a little while the problem is still present.

`Could not acquire lock(s)`

I am switching back to `-Daether.syncContext.named.factory=file-lock -Daether.syncContext.named.nameMapper=file-gav`

This is not perfect but at least it hasn't reproduced the problem for a considerably long period of time.

**Comment by eliasbalasis** [comment]
`-Daether.named.diagnostic.enabled=true` did not reveal much, except detailed list of the active locks.

However, I was using the `rwlock-redisson` named locks factory.

I will try with other named lock factories.

**Comment by eliasbalasis** [comment]
`semaphore-redisson` named locks factory did not work either.

I will try with Hazelcast name locks factory.

**Comment by cstamas** [comment]
The point of "diagnostic" is exactly that, please paste it into gist and put it here....

**Comment by eliasbalasis** [comment]
@cstamas,
I cannot share the build output because it contains references to private components.

Specifically for "redisson" named lock implementation, trust me when I say that the build output did not reveal much except detailed list of the active locks.
It contains only the list of locks at the time of failure and no stack trace or any detailed analysis of the errors.
Therefore it is pointless for me trying to cleanup the build output by removing the references to private references.

I observed this repeatedly using "gav" , "discriminating" name mappers.
(see https://maven.apache.org/resolver/maven-resolver-named-locks/index.html)

However, the "static" name mapper seems to be the only one working without producing any locking errors.
This is great progress from where I stand.

I am now trying to experiment with "hazelcast" named lock implementation and I intend to share the outcome.

**Comment by cstamas** [comment]
At least you can do following as written here:
https://github.com/apache/maven-mvnd/issues/836#issuecomment-1706549388

You should be able to identity your "hot artifact", if you have one.

**Comment by eliasbalasis** [comment]
@cstamas,
I am using "aether.named.diagnostic.enabled=true"
which now seems to be working after upgrading to Maven 3.9.x

Also, identifying the hot artifact is easy.
It is included in the build output and it is different on every build.
However, this is not the problem I am trying to resolve.

The problem I have been trying to resolve for a long time,
is the Maven distributed locks malfunction,
which didn't seem to be working before Maven 3.9.x but seems to be working now,
with "static" name mapper and "redisson" named lock implementation.

**Comment by eliasbalasis** [comment]
I spoke too soon.
It is still not working.


```
MAVEN_OPTS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Daether.syncContext.named.factory=rwlock-redisson -Daether.syncContext.named.nameMapper=static -Daether.named.diagnostic.enabled=true
...
...
...
mvn -B clean install -Dmaven.logging=byproject --builder smart -T 1C
...
...
...
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
...
...
...
Java version: 17.0.10, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17-oracle-x64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.18.0-513.18.0.1.el8_9.x86_64", arch: "amd64", family: "unix"
...
...
...
Redisson 3.23.4
1 connections initialized for <host>/<ip>:<port>
24 connections initialized for <host>/<ip>:<port>
...
...
...
Using the SmartBuilder implementation with a thread count of 12
...
...
...
Diagnostic dump of lock factory
===============================
Implementation: org.eclipse.aether.named.redisson.RedissonReadWriteLockNamedLockFactory
Active locks: 1

Name: static-artifact
RefCount: 7
  Thread[BuilderThread 5,5,] -> []
  Thread[BuilderThread 8,5,] -> []
  Thread[BuilderThread 7,5,] -> []
  Thread[BuilderThread 2,5,] -> []
  Thread[BuilderThread 1,5,] -> []
  Thread[resolver-1,5,org.apache.maven.artifact.resolver.DefaultArtifactResolver] -> []
  Thread[BuilderThread 11,5,] -> []
  Thread[resolver-3,5,org.apache.maven.artifact.resolver.DefaultArtifactResolver] -> []
  Thread[BuilderThread 0,5,] -> []
  Thread[BuilderThread 9,5,] -> []
  Thread[BuilderThread 10,5,] -> []
  Thread[BuilderThread 6,5,] -> []
  Thread[resolver-5,5,org.apache.maven.artifact.resolver.DefaultArtifactResolver] -> []
  Thread[BuilderThread 4,5,] -> []
  Thread[resolver-2,5,org.apache.maven.artifact.resolver.DefaultArtifactResolver] -> []
  Thread[resolver-4,5,org.apache.maven.artifact.resolver.DefaultArtifactResolver] -> []
  Thread[BuilderThread 3,5,] -> []

------------------------------------------------------------------------
Reactor Summary for <top level artifactId>:
...
...
...
Could not acquire lock(s)
<the hot artifactId>: Could not acquire lock(s)
...
...
...
To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.
Redisson 3.23.4
1 connections initialized for <host>/<ip>:<port>
24 connections initialized for <host>/<ip>:<port>
...
...
...
```

As pointed out, no error details

**Comment by drj101687** [comment]
I just ran into a similar issue related to dependency locks on Windows 11. The issue only happened with `mvnd`. 

It started after I changed my environment variables to use a different JDK. I tried deleting the .locks and they kept returning. I tried deleting cached dependencies from the repository cache, but related jars were somehow still open with my previous JDK.

I restarted my machine and noticed that the .lock files were no longer returning and I was able to delete the related dependency jars from the cache. After that, `mvnd` worked perfectly and I no longer saw the .lock files get "stuck". 

I have no clue how related my issue is with other issues in this thread, but maybe my steps help someone else.

**Comment by kah-ell** [comment]
Also seems to happen on Linux. Happened while downloading dependencies from the command:
```                                                                                                                                          
clj -Sdeps '{:deps {vlaaad/reveal {:mvn/version "1.3.284"}}}' -X vlaaad.reveal/repl
```

First few lines of exception:
```
Error building classpath. Could not acquire write lock for 'artifact:org.openjfx:javafx-web:22-ea+16'
java.lang.IllegalStateException: Could not acquire write lock for 'artifact:org.openjfx:javafx-web:22-ea+16'
        at org.eclipse.aether.internal.impl.synccontext.named.NamedLockFactoryAdapter$AdaptedLockSyncContext.acquire(NamedLockFactoryAdapter.java:165)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:233)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:272)
```
