### ISSUE TITLE
I am using the alias to switch jdk, 0.7.1 is ok, but 0.9.0 has problem

### ISSUE THREAD

**Issue by winhkey** [apache/maven-mvnd#837]
export JAVA_8_HOME=/usr/local/program/jdk/jdk1.8.0_281
export JAVA_17_HOME=/usr/local/program/jdk/jdk-17.0.6
alias jdk8="export JAVA_HOME=$JAVA_8_HOME"
alias jdk17="export JAVA_HOME=$JAVA_17_HOME"

CentOS Linux release 7.6.1810 (Core)
0.7.1:
[root@localhost ~]# mvnd -v
mvnd native client 0.7.1-linux-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /usr/local/program/maven/mvnd-0.7.1-linux-amd64/mvn
Java version: 17.0.6, vendor: Oracle Corporation, runtime: /usr/local/program/jdk/jdk-17.0.6
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.el7.x86_64", arch: "amd64", family: "unix"

0.9.0:
[root@localhost ~]# mvnd -v
Apache Maven Daemon (mvnd) 0.9.0 linux-amd64 native client (fa3cc5d66458a8526bd543de85566293113dacc4)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Exception in thread "main" java.lang.RuntimeException: Could not get a real path from path $JAVA_HOME
        at org.mvndaemon.mvnd.client.DaemonParameters.javaHome(DaemonParameters.java:150)
        at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:101)
        at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:327)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:153)

**Comment by winhkey** [comment]
> @winhkey Could you try with a recent `mvnd` version and report ?

I have updated the recent version, but got the same exception
<img width="884" alt="image" src="https://github.com/apache/maven-mvnd/assets/4877808/e4840bdc-f21f-492b-95c9-4cd3b3d25783">
