### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by sp-personal** [apache/maven-mvnd#875]
Might anyone know offhand what this error is??

The last 3 MVND releases have been doing this.  It just seems to blow up when it starts...
-----------

17:16:58 OpenJDK 64-Bit Server VM (build 17.0.3.1+2-LTS, mixed mode, sharing)
17:16:58 + echo MAVEN_HOME=
17:16:58 MAVEN_HOME=
17:16:58 + which mvn
17:16:58 /home/ec2-user/jenkins/tools/mavend/bin/mvn
17:16:58 + mvn -version
17:17:02 Aug 03, 2023 5:17:02 PM org.jline.utils.Log logr
17:17:02 WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
17:17:02 [main] [1;33mWARNING[m org.jline - Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
17:17:02 Apache Maven Daemon (mvnd) 1.0-m7 linux-amd64 native client (b2ef5d81997adbcdb72dc8c5603722538fa641fe)
17:17:02 Terminal: org.jline.terminal.impl.DumbTerminal
17:17:12 Exception in thread "main" org.mvndaemon.mvnd.common.DaemonException$ConnectException: Timeout waiting to connect to the Maven daemon.
17:17:12 Daemon id: 291a4db7
17:17:12   no log file at: /home/ec2-user/.m2/mvnd/registry/1.0-m7/daemon-291a4db7.log
17:17:12   output: /home/ec2-user/.m2/mvnd/registry/1.0-m7/daemon-291a4db7.out.log
17:17:12 ----- Last  200 lines from daemon output - /home/ec2-user/.m2/mvnd/registry/1.0-m7/daemon-291a4db7.out.log -----
17:17:12 Starting daemon process: id = 291a4db7, workingDir = /mnt/data/home/ec2-user/jenkins/workspace/Cortex/1.4/Build_Dev, daemonArgs: /home/build/jenkins/tools/jdk-17.0.2/bin/java -classpath /mnt/data/home/ec2-user/.sdkman/candidates/mvnd/1.0-m7-m39/mvn/boot/plexus-classworlds-2.7.0.jar -javaagent:/mnt/data/home/ec2-user/.sdkman/candidates/mvnd/1.0-m7-m39/mvn/lib/mvnd/mvnd-agent-1.0-m7.jar -Xms3G -Dmvnd.home=/mnt/data/home/ec2-user/.sdkman/candidates/mvnd/1.0-m7-m39 -Dmaven.home=/mnt/data/home/ec2-user/.sdkman/candidates/mvnd/1.0-m7-m39/mvn -Dmaven.conf=/mnt/data/home/ec2-user/.sdkman/candidates/mvnd/1.0-m7-m39/mvn/conf -Dclassworlds.conf=/mnt/data/home/ec2-user/.sdkman/candidates/mvnd/1.0-m7-m39/bin/mvnd-daemon.conf -Dorg.slf4j.simpleLogger.logFile=/home/ec2-user/.m2/mvnd/registry/1.0-m7/daemon-291a4db7.log -Dmvnd.java.home=/home/build/jenkins/tools/jdk-17.0.2 -Dmvnd.id=291a4db7 -Dmvnd.daemonStorage=/home/ec2-user/.m2/mvnd/registry/1.0-m7 -Dmvnd.registry=/home/ec2-user/.m2/mvnd/registry/1.0-m7/registry.bin -Dmvnd.socketFamily=inet -Dmvnd.home=/mnt/data/home/ec2-user/.sdkman/candidates/mvnd/1.0-m7-m39 -Djdk.java.options=--add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Dmvnd.noDaemon=false -Dmvnd.debug=false -Dmvnd.debug.address=8000 -Dmvnd.idleTimeout=3h -Dmvnd.keepAlive=10s -Dmvnd.extClasspath= -Dmvnd.coreExtensions= -Dmvnd.minHeapSize=3G -Dmvnd.enableAssertions=false -Dmvnd.expirationCheckDelay=10s -Dmvnd.duplicateDaemonGracePeriod=10s -Dmvnd.socketFamily=inet org.codehaus.plexus.classworlds.launcher.LauncherNOTE: Picked up JDK_JAVA_OPTIONS: --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED
17:17:12 ----- End of the daemon output -----
17:17:12 
17:17:12 	at org.mvndaemon.mvnd.client.DaemonConnector.startDaemon(DaemonConnector.java:330)
17:17:12 	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:123)
17:17:12 	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:339)
17:17:12 	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:161)
17:17:12 Build step 'Execute shell' marked build as failure

**Comment by sp-personal** [comment]
Tracked this down to inadequate min heap size...

setting mvnd.minHeapSize = 9G

Seems to have fixed the issue...

**Comment by sp-personal** [comment]
Closing to reduce annoyances
